import sqlite3
import json
import os
import glob

drugs_data = [
    {
        "name": "Benzyl Penicillin (Penicillin G) — بنسيلين جي",
        "category": "المضادات الحيوية (Antibiotics)",
        "forms": ["حقنة"],
        "doses_adult": ["1–5 مليون وحدة كل 6 ساعات (عضلي أو وريدي)"],
        "doses_child": ["50,000–100,000 وحدة/كغ/يوم (عضلي أو وريدي)"],
        "doses_elderly": ["تعديل الجرعة حسب حالة الكلى"],
        "timing": ["كل 6 ساعات"],
        "duration": ["7–14 يوم"],
        "note": "قد يسبب صدمة تأقية — يُبقى الأدرينالين جاهزاً. الجرعات الكبيرة خطرة عند القصور الكلوي والقلبي.",
        "warn_pregnant": "مسموح",
        "warn_breastfeed": "مسموح",
        "warn_renal": "تعديل الجرعة مطلوب - خطر الجرعات العالية",
        "warn_hepatic": "",
        "warn_allergy": "يُسأل عن تاريخ الحساسية بدقة - صدمة تأقية محتملة",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Benzathine Penicillin (Retarpen) — بنزاثين بنسيلين",
        "category": "المضادات الحيوية (Antibiotics)",
        "forms": ["حقنة"],
        "doses_adult": ["1.2–2.4 مليون وحدة عضلي كل 1–4 أسابيع"],
        "doses_child": ["50,000 وحدة/كغ عضلي"],
        "doses_elderly": ["حسب الحالة"],
        "timing": ["مرة كل 1–4 أسابيع"],
        "duration": ["وقائي لسنوات"],
        "note": "حقن عضلي فقط. لا يُعطى وريدياً أبداً.",
        "warn_pregnant": "مسموح",
        "warn_breastfeed": "مسموح",
        "warn_renal": "",
        "warn_hepatic": "",
        "warn_allergy": "اختبار الحساسية مهم جداً قبل الإعطاء",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Phenoxymethyl Penicillin (Ospen) — بنسيلين V",
        "category": "المضادات الحيوية (Antibiotics)",
        "forms": ["أقراص", "شراب"],
        "doses_adult": ["250–500 ملغ كل 4 ساعات فموياً"],
        "doses_child": ["50,000 وحدة/كغ/يوم فموياً"],
        "doses_elderly": ["حسب الحالة"],
        "timing": ["كل 4 ساعات"],
        "duration": ["7–10 أيام"],
        "note": "يُفضل أخذه على معدة فارغة لزيادة الامتصاص.",
        "warn_pregnant": "مسموح — آمن نسبياً",
        "warn_breastfeed": "مسموح",
        "warn_renal": "",
        "warn_hepatic": "",
        "warn_allergy": "حساسية متقاطعة مع السيفالوسبورينات بنسبة 10%",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Amoxicillin (E-mox) — أموكسيسيلين",
        "category": "المضادات الحيوية (Antibiotics)",
        "forms": ["كبسول", "شراب"],
        "doses_adult": ["250–500 ملغ × 3/يوم"],
        "doses_child": ["20–40 ملغ/كغ/يوم مقسمة كل 8 ساعات"],
        "doses_elderly": ["حسب الحالة"],
        "timing": ["كل 8 ساعات"],
        "duration": ["5–10 أيام"],
        "note": "لا يتأثر بالطعام. طفح جلدي في 10% من المرضى.",
        "warn_pregnant": "مسموح",
        "warn_breastfeed": "مسموح",
        "warn_renal": "",
        "warn_hepatic": "",
        "warn_allergy": "حساسية متقاطعة مع السيفالوسبورينات 10%",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Amoxicillin + Clavulanic Acid (Augmentin) — أوجمنتين",
        "category": "المضادات الحيوية (Antibiotics)",
        "forms": ["أقراص", "شراب", "حقنة"],
        "doses_adult": ["625 ملغ × 3/يوم أو 1000 ملغ × 2/يوم"],
        "doses_child": ["25–50 ملغ/كغ/يوم (أموكسيسيلين) مقسمة كل 8 ساعات"],
        "doses_elderly": ["تعديل الجرعة في القصور الكلوي الشديد"],
        "timing": ["مع بداية الوجبة"],
        "duration": ["5–14 يوم"],
        "note": "يؤخذ في بداية الوجبة لتقليل الآثار الجانبية الهضمية.",
        "warn_pregnant": "مسموح",
        "warn_breastfeed": "مسموح",
        "warn_renal": "تعديل الجرعة مطلوب في القصور الشديد",
        "warn_hepatic": "حذر — ممنوع عند اليرقان الكبدي السابق من الأوجمنتين",
        "warn_allergy": "حساسية بنسيلين",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Ampicillin (Epicocillin) — أمبيسيلين",
        "category": "المضادات الحيوية (Antibiotics)",
        "forms": ["كبسول", "حقنة"],
        "doses_adult": ["1–2 غ/يوم مقسمة"],
        "doses_child": ["50–100 ملغ/كغ/يوم مقسمة كل 6 ساعات"],
        "doses_elderly": ["حسب الحالة"],
        "timing": ["كل 6 ساعات على معدة فارغة"],
        "duration": ["7–14 يوم"],
        "note": "يؤخذ قبل الأكل بساعة. طفح جلدي في 100% عند مرضى كثرة الوحيدات العدوائية.",
        "warn_pregnant": "مسموح",
        "warn_breastfeed": "مسموح",
        "warn_renal": "",
        "warn_hepatic": "",
        "warn_allergy": "حساسية بنسيلين",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Cloxacillin / Flucloxacillin — كلوكساسيلين",
        "category": "المضادات الحيوية (Antibiotics)",
        "forms": ["كبسول", "شراب", "حقنة"],
        "doses_adult": ["250–500 ملغ كل 6 ساعات"],
        "doses_child": ["12.5–25 ملغ/كغ كل 6 ساعات"],
        "doses_elderly": ["حسب الحالة"],
        "timing": ["كل 6 ساعات على معدة فارغة"],
        "duration": ["7–14 يوم"],
        "note": "يُستخدم خصيصاً ضد المكورات العنقودية.",
        "warn_pregnant": "مسموح بحذر",
        "warn_breastfeed": "مسموح",
        "warn_renal": "",
        "warn_hepatic": "",
        "warn_allergy": "حساسية بنسيلين",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Cephalexin (Zinnat/Keflex) — سيفالكسين",
        "category": "المضادات الحيوية (Antibiotics)",
        "forms": ["أقراص", "شراب", "حقنة"],
        "doses_adult": ["250–500 ملغ كل 6 ساعات"],
        "doses_child": ["25–50 ملغ/كغ/يوم مقسمة 3-4 جرعات"],
        "doses_elderly": ["تعديل الجرعة في القصور الكلوي"],
        "timing": ["كل 6–8 ساعات"],
        "duration": ["7–10 أيام"],
        "note": "جيل أول من السيفالوسبورينات. لا يُفيد في التهاب السحايا.",
        "warn_pregnant": "مسموح",
        "warn_breastfeed": "مسموح",
        "warn_renal": "تعديل الجرعة عند القصور",
        "warn_hepatic": "",
        "warn_allergy": "حساسية متقاطعة مع البنسيلين 10%",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Cefuroxime (Zinnat) — سيفوروكسيم",
        "category": "المضادات الحيوية (Antibiotics)",
        "forms": ["أقراص", "شراب", "حقنة"],
        "doses_adult": ["250–500 ملغ × 2/يوم"],
        "doses_child": ["20–40 ملغ/كغ/يوم مقسمة كل 12 ساعة"],
        "doses_elderly": ["تعديل الجرعة في القصور الكلوي"],
        "timing": ["كل 8–12 ساعة مع الطعام"],
        "duration": ["7–10 أيام"],
        "note": "جيل ثاني. يخترق الحاجز الدماغي جزئياً.",
        "warn_pregnant": "مسموح",
        "warn_breastfeed": "مسموح",
        "warn_renal": "تعديل الجرعة مطلوب",
        "warn_hepatic": "",
        "warn_allergy": "حساسية سيفالوسبورينات",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Ceftriaxone (Rocephin) — سيفيترياكسون",
        "category": "المضادات الحيوية (Antibiotics)",
        "forms": ["حقنة"],
        "doses_adult": ["1–2 غ مرة/يوم أو مقسمة"],
        "doses_child": ["20–100 ملغ/كغ/يوم حسب الحالة"],
        "doses_elderly": ["لا يحتاج تعديل جرعة كلوية"],
        "timing": ["مرة أو مرتين يومياً"],
        "duration": ["7–14 يوم"],
        "note": "جيل ثالث. يُطرح بالصفراء. يُتجنب عند الوليد إذا يُعطى الكالسيوم وريدياً.",
        "warn_pregnant": "مسموح",
        "warn_breastfeed": "مسموح",
        "warn_renal": "لا يحتاج تعديل جرعة",
        "warn_hepatic": "حذر في القصور الشديد",
        "warn_allergy": "حساسية سيفالوسبورينات",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Cefixime (Suprax) — سيفيكسيم",
        "category": "المضادات الحيوية (Antibiotics)",
        "forms": ["أقراص", "شراب"],
        "doses_adult": ["200–400 ملغ × 1–2/يوم"],
        "doses_child": ["8 ملغ/كغ/يوم جرعة واحدة أو مقسمة"],
        "doses_elderly": ["تعديل الجرعة في القصور الكلوي"],
        "timing": ["مرة أو مرتين يومياً"],
        "duration": ["7–14 يوم"],
        "note": "جيل ثالث فموي واسع الطيف.",
        "warn_pregnant": "مسموح",
        "warn_breastfeed": "مسموح",
        "warn_renal": "تعديل الجرعة مطلوب",
        "warn_hepatic": "",
        "warn_allergy": "حساسية سيفالوسبورينات",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Cefepime (Maxipime) — سيفيبيم",
        "category": "المضادات الحيوية (Antibiotics)",
        "forms": ["حقنة"],
        "doses_adult": ["1–2 غ كل 8–12 ساعة"],
        "doses_child": ["50 ملغ/كغ كل 12 ساعة (كل 8 في الشديد)"],
        "doses_elderly": ["تعديل الجرعة ضروري"],
        "timing": ["كل 8–12 ساعة وريدي"],
        "duration": ["7–10 أيام"],
        "note": "جيل رابع. أقوى مقاومة للبيتا لاكتاماز.",
        "warn_pregnant": "مسموح",
        "warn_breastfeed": "مسموح",
        "warn_renal": "تعديل الجرعة ضروري",
        "warn_hepatic": "",
        "warn_allergy": "حساسية سيفالوسبورينات",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Meropenem (Meronam) — ميروبينيم",
        "category": "المضادات الحيوية (Antibiotics)",
        "forms": ["حقنة"],
        "doses_adult": ["500 ملغ–1 غ 3 مرات/يوم وريدي/عضلي"],
        "doses_child": ["حسب الحالة بإشراف طبي متخصص"],
        "doses_elderly": ["تعديل الجرعة في القصور الكلوي"],
        "timing": ["كل 8 ساعات"],
        "duration": ["7–14 يوم"],
        "note": "كاربابينيم واسع الطيف للعدوى الخطيرة والمقاومة.",
        "warn_pregnant": "بحذر شديد",
        "warn_breastfeed": "بحذر",
        "warn_renal": "تعديل الجرعة مطلوب",
        "warn_hepatic": "",
        "warn_allergy": "حذر عند حساسية البنسيلين الشديدة",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Erythromycin (Erythrocin) — إيريثرومايسين",
        "category": "المضادات الحيوية (Antibiotics)",
        "forms": ["أقراص", "شراب", "حقنة"],
        "doses_adult": ["250–500 ملغ كل 6 ساعات"],
        "doses_child": ["30–50 ملغ/كغ/يوم مقسمة 3-4 جرعات"],
        "doses_elderly": ["حسب الحالة"],
        "timing": ["كل 6 ساعات قبل الطعام"],
        "duration": ["7–14 يوم"],
        "note": "بديل آمن للبنسيلين. يرفع مستوى الوارفارين والثيوفيلين.",
        "warn_pregnant": "مسموح",
        "warn_breastfeed": "مسموح بحذر",
        "warn_renal": "",
        "warn_hepatic": "حذر عند قصور الكبد",
        "warn_allergy": "حساسية ماكروليدات",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Azithromycin (Zithromax) — أزيثرومايسين",
        "category": "المضادات الحيوية (Antibiotics)",
        "forms": ["أقراص", "شراب", "حقنة"],
        "doses_adult": ["500 ملغ يومياً لمدة 3 أيام"],
        "doses_child": ["10 ملغ/كغ/يوم جرعة واحدة"],
        "doses_elderly": ["حذر عند مرضى القلب (تطويل QT)"],
        "timing": ["مرة واحدة يومياً"],
        "duration": ["3–5 أيام"],
        "note": "أقل تفاعلات دوائية من الإيريثرومايسين.",
        "warn_pregnant": "مسموح بإشراف طبي",
        "warn_breastfeed": "بحذر",
        "warn_renal": "",
        "warn_hepatic": "",
        "warn_allergy": "حساسية ماكروليدات",
        "warn_diabetes": "",
        "warn_blood_pressure": "حذر عند مرضى القلب (تطويل QT)"
    },
    {
        "name": "Clarithromycin (Klacid) — كلاريثرومايسين",
        "category": "المضادات الحيوية (Antibiotics)",
        "forms": ["أقراص", "شراب"],
        "doses_adult": ["250–500 ملغ × 2/يوم"],
        "doses_child": ["15 ملغ/كغ/يوم مقسمة كل 12 ساعة"],
        "doses_elderly": ["تعديل الجرعة في القصور الكلوي"],
        "timing": ["كل 12 ساعة"],
        "duration": ["7–14 يوم"],
        "note": "يُطرح صفراوياً. يتفاعل مع العديد من الأدوية.",
        "warn_pregnant": "يُتجنب — تأثير مشوّه على الجنين",
        "warn_breastfeed": "بحذر",
        "warn_renal": "تعديل الجرعة مطلوب",
        "warn_hepatic": "حذر عند قصور الكبد",
        "warn_allergy": "حساسية ماكروليدات",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Gentamicin (Garamycin) — جنتامايسين",
        "category": "المضادات الحيوية (Antibiotics)",
        "forms": ["حقنة", "قطرة"],
        "doses_adult": ["3–5 ملغ/كغ/يوم مقسمة كل 8 ساعات"],
        "doses_child": ["3–5 ملغ/كغ/يوم مقسمة كل 8 ساعات"],
        "doses_elderly": ["تعديل الجرعة ضروري جداً"],
        "timing": ["كل 8 ساعات وريدي أو عضلي"],
        "duration": ["7–10 أيام كحد أقصى"],
        "note": "سمية سمعية وكلوية دائمية. لا يخلط مع البنسيلين في نفس المحقنة.",
        "warn_pregnant": "ممنوع — يسبب صمماً للجنين",
        "warn_breastfeed": "ممنوع",
        "warn_renal": "سمية كلوية عالية — تعديل الجرعة ومراقبة",
        "warn_hepatic": "",
        "warn_allergy": "حساسية أمينوغليكوزيدات",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Ciprofloxacin (Cipro) — سيبروفلوكساسين",
        "category": "المضادات الحيوية (Antibiotics)",
        "forms": ["أقراص", "حقنة", "قطرة"],
        "doses_adult": ["250–750 ملغ × 2/يوم فموياً"],
        "doses_child": ["ممنوع عموماً أقل من 18 سنة"],
        "doses_elderly": ["حذر — خطر تمزق وتر أكيلس"],
        "timing": ["كل 12 ساعة"],
        "duration": ["7–14 يوم"],
        "note": "يتلف الغضاريف عند الأطفال. يتفاعل مع مضادات الحموضة والحديد.",
        "warn_pregnant": "ممنوع",
        "warn_breastfeed": "ممنوع",
        "warn_renal": "تعديل الجرعة مطلوب",
        "warn_hepatic": "",
        "warn_allergy": "حساسية كينولونات",
        "warn_diabetes": "",
        "warn_blood_pressure": "حذر عند مرضى الصرع (تشنجات)"
    },
    {
        "name": "Levofloxacin (Tavanic) — ليفوفلوكساسين",
        "category": "المضادات الحيوية (Antibiotics)",
        "forms": ["أقراص", "حقنة"],
        "doses_adult": ["500–750 ملغ × 1/يوم"],
        "doses_child": ["ممنوع أقل من 18 سنة"],
        "doses_elderly": ["حسب الحالة"],
        "timing": ["مرة واحدة يومياً"],
        "duration": ["5–14 يوم"],
        "note": "كينولون تنفسي يؤخذ مرة واحدة يومياً.",
        "warn_pregnant": "ممنوع",
        "warn_breastfeed": "ممنوع",
        "warn_renal": "تعديل الجرعة مطلوب",
        "warn_hepatic": "",
        "warn_allergy": "حساسية كينولونات",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Co-Trimoxazole (Sutrim) — سوتريم",
        "category": "المضادات الحيوية (Antibiotics)",
        "forms": ["أقراص", "شراب", "حقنة"],
        "doses_adult": ["قرص 960 ملغ × 2/يوم"],
        "doses_child": ["0.5–1 مل/كغ/يوم مقسمة كل 12 ساعة"],
        "doses_elderly": ["تعديل الجرعة في القصور الكلوي"],
        "timing": ["كل 12 ساعة مع الكثير من الماء"],
        "duration": ["5–14 يوم"],
        "note": "ممنوع عند مرضى G6PD. قد يسبب متلازمة ستيفن جونسون.",
        "warn_pregnant": "ممنوع — يضر الجنين",
        "warn_breastfeed": "ممنوع",
        "warn_renal": "ممنوع عند القصور الشديد",
        "warn_hepatic": "حذر",
        "warn_allergy": "حساسية سلفا",
        "warn_diabetes": "حذر — تفاعل مع أدوية السكر",
        "warn_blood_pressure": ""
    },
    {
        "name": "Doxycycline (Vibramycin) — دوكسيسيكلين",
        "category": "المضادات الحيوية (Antibiotics)",
        "forms": ["أقراص"],
        "doses_adult": ["100 ملغ × 2 أول يوم ثم 100 ملغ مرة يومياً"],
        "doses_child": ["ممنوع أقل من 8 سنوات"],
        "doses_elderly": ["حسب الحالة"],
        "timing": ["مرة أو مرتين يومياً"],
        "duration": ["7–14 يوم"],
        "note": "يتلف الأسنان عند الأطفال ويعيق نمو العظام. حساسية للضوء.",
        "warn_pregnant": "ممنوع",
        "warn_breastfeed": "ممنوع",
        "warn_renal": "",
        "warn_hepatic": "",
        "warn_allergy": "حساسية تتراسيكلين",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Chloramphenicol — كلورامفينيكول",
        "category": "المضادات الحيوية (Antibiotics)",
        "forms": ["أقراص", "حقنة", "قطرة"],
        "doses_adult": ["500 ملغ كل 6 ساعات"],
        "doses_child": ["25–50 ملغ/كغ/يوم مقسمة كل 6 ساعات"],
        "doses_elderly": ["حسب الحالة"],
        "timing": ["كل 6 ساعات"],
        "duration": ["10–14 يوم"],
        "note": "يسبب متلازمة الطفل الرمادي للمواليد. يثبط نخاع العظم.",
        "warn_pregnant": "ممنوع",
        "warn_breastfeed": "ممنوع",
        "warn_renal": "",
        "warn_hepatic": "حذر شديد",
        "warn_allergy": "",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Clindamycin (Dalacin-C) — كليندامايسين",
        "category": "المضادات الحيوية (Antibiotics)",
        "forms": ["كبسول", "حقنة", "جل"],
        "doses_adult": ["300 ملغ كل 6 ساعات فموياً"],
        "doses_child": ["10–30 ملغ/كغ/يوم مقسمة 3-4 جرعات"],
        "doses_elderly": ["حسب الحالة"],
        "timing": ["كل 6–8 ساعات"],
        "duration": ["7–14 يوم"],
        "note": "خطر التهاب القولون الكاذب. يوقف فوراً عند حدوث إسهال شديد.",
        "warn_pregnant": "بحذر",
        "warn_breastfeed": "مسموح بحذر",
        "warn_renal": "",
        "warn_hepatic": "حذر عند القصور الكبدي",
        "warn_allergy": "حساسية لينكوزامينات",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    }
]

def main():
    db_files = glob.glob(r"c:\Users\Dell\Desktop\claude 1 - Copy - Copy - Copy\dental-clinic\backend\clinic*.db")
    if not db_files:
        print("No database files found!")
        return

    for db_path in db_files:
        print(f"\nSeeding database: {os.path.basename(db_path)}")
        conn = sqlite3.connect(db_path)
        cur = conn.cursor()
        
        count = 0
        for d in drugs_data:
            try:
                # Ensure table exists and columns exist
                cur.execute("""
                    CREATE TABLE IF NOT EXISTS drugs (
                        id INTEGER PRIMARY KEY AUTOINCREMENT, 
                        name TEXT UNIQUE, 
                        category TEXT, 
                        forms TEXT, 
                        doses_adult TEXT, 
                        doses_child TEXT, 
                        doses_elderly TEXT, 
                        timing TEXT, 
                        duration TEXT, 
                        note TEXT, 
                        warn_pregnant TEXT, 
                        warn_breastfeed TEXT, 
                        warn_renal TEXT, 
                        warn_hepatic TEXT, 
                        warn_allergy TEXT, 
                        warn_diabetes TEXT, 
                        warn_blood_pressure TEXT, 
                        is_custom INTEGER DEFAULT 0
                    )
                """)
                
                cur.execute("""
                    INSERT INTO drugs (name, category, forms, doses_adult, doses_child, doses_elderly, timing, duration, note, warn_pregnant, warn_breastfeed, warn_renal, warn_hepatic, warn_allergy, warn_diabetes, warn_blood_pressure, is_custom)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1)
                """, (
                    d["name"], d["category"],
                    json.dumps(d["forms"], ensure_ascii=False),
                    json.dumps(d["doses_adult"], ensure_ascii=False),
                    json.dumps(d["doses_child"], ensure_ascii=False),
                    json.dumps(d["doses_elderly"], ensure_ascii=False),
                    json.dumps(d["timing"], ensure_ascii=False),
                    json.dumps(d["duration"], ensure_ascii=False),
                    d["note"], d["warn_pregnant"], d["warn_breastfeed"],
                    d["warn_renal"], d["warn_hepatic"],
                    d["warn_allergy"], d["warn_diabetes"], d["warn_blood_pressure"]
                ))
                count += 1
            except sqlite3.IntegrityError:
                pass
            except Exception as e:
                print(f"Error inserting {d['name']}: {e}")

        conn.commit()
        conn.close()
        print(f"Successfully inserted {count} NEW Antibiotics into {os.path.basename(db_path)}!")

if __name__ == "__main__":
    main()
