import sqlite3
import json
import os

db_path = "clinic.db"

drugs_data = [
    {
        "name": "Paracetamol (Acetaminophen) - باراسيتامول",
        "category": "المسكنات (Analgesics)",
        "forms": ["أقراص", "شراب", "تحاميل", "حقنة"],
        "doses_adult": ["500–1000mg"],
        "doses_child": ["10–15mg/kg"],
        "doses_elderly": [],
        "timing": ["كل 4-6 ساعات"],
        "duration": ["1-3 أيام"],
        "note": "الحد الأقصى 4 غ/يوم. لا تتجاوز الجرعة لتجنب سمية الكبد.",
        "warn_pregnant": "مسموح",
        "warn_breastfeed": "مسموح",
        "warn_renal": "",
        "warn_hepatic": "ممنوع عند قصور الكبد الشديد",
        "warn_allergy": "",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Metamizol - ميتاميزول (ديبيرون)",
        "category": "المسكنات (Analgesics)",
        "forms": ["أقراص", "حقنة"],
        "doses_adult": ["500mg"],
        "doses_child": [],
        "doses_elderly": [],
        "timing": ["كل 6-8 ساعات"],
        "duration": ["أقصر مدة ممكنة"],
        "note": "ممنوع في كثير من الدول بسبب السمية. يسبب فقر دم ونقص كريات الدم البيضاء.",
        "warn_pregnant": "ممنوع",
        "warn_breastfeed": "",
        "warn_renal": "",
        "warn_hepatic": "",
        "warn_allergy": "يسبب حساسية شديدة",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Nefopam - نيفوبام",
        "category": "المسكنات (Analgesics)",
        "forms": ["أقراص", "حقنة"],
        "doses_adult": ["20mg"],
        "doses_child": [],
        "doses_elderly": [],
        "timing": ["كل 6-8 ساعات"],
        "duration": ["حسب الحاجة"],
        "note": "أقوى من NSAIDs وقريب من قوة المورفين. قد يسبب تسرع قلب وتعرق.",
        "warn_pregnant": "يُتجنب",
        "warn_breastfeed": "",
        "warn_renal": "",
        "warn_hepatic": "",
        "warn_allergy": "",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Aspirin (Acetylsalicylic acid) - أسبرين",
        "category": "المسكنات (Analgesics)",
        "forms": ["أقراص"],
        "doses_adult": ["300–1000mg (مسكن)", "75–100mg (مضاد تجلط)"],
        "doses_child": [],
        "doses_elderly": [],
        "timing": ["مرة واحدة يومياً", "كل 4-6 ساعات"],
        "duration": ["1-3 أيام"],
        "note": "الأطفال <16 سنة: ممنوع تماماً. يرفع اليوريك أسيد.",
        "warn_pregnant": "ممنوع في الثلث الأخير",
        "warn_breastfeed": "يُتجنب",
        "warn_renal": "ممنوع عند القصور الكلوي الشديد",
        "warn_hepatic": "",
        "warn_allergy": "يُتجنب لمرضى الربو",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Ibuprofen - إيبوبروفين",
        "category": "المسكنات (Analgesics)",
        "forms": ["أقراص", "شراب", "جل"],
        "doses_adult": ["200-400mg"],
        "doses_child": ["5-10mg/kg"],
        "doses_elderly": [],
        "timing": ["ثلاث مرات يومياً"],
        "duration": ["3-5 أيام"],
        "note": "يسبب قرحة معدية. الأفضل لألم الأسنان.",
        "warn_pregnant": "ممنوع في الثلث الأخير",
        "warn_breastfeed": "يُتجنب",
        "warn_renal": "تخفيض الجرعة",
        "warn_hepatic": "",
        "warn_allergy": "ممنوع لمرضى الربو",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Diclofenac (Voltaren/Cataflam) - ديكلوفيناك",
        "category": "المسكنات (Analgesics)",
        "forms": ["أقراص", "حقنة", "جل", "تحاميل"],
        "doses_adult": ["50mg"],
        "doses_child": ["1-2mg/kg"],
        "doses_elderly": [],
        "timing": ["مرتان يومياً", "ثلاث مرات يومياً"],
        "duration": ["3-7 أيام"],
        "note": "قرحة معدية - يؤخذ مع الطعام.",
        "warn_pregnant": "ممنوع في الثلث الأخير",
        "warn_breastfeed": "",
        "warn_renal": "حذر",
        "warn_hepatic": "حذر",
        "warn_allergy": "يُتجنب لمرضى الربو",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Naproxen - نابروكسين",
        "category": "المسكنات (Analgesics)",
        "forms": ["أقراص"],
        "doses_adult": ["250-500mg"],
        "doses_child": ["5-7mg/kg"],
        "doses_elderly": [],
        "timing": ["مرتان يومياً"],
        "duration": ["5-7 أيام"],
        "note": "الأقل تأثيراً على القلب.",
        "warn_pregnant": "ممنوع في الثلث الأخير",
        "warn_breastfeed": "",
        "warn_renal": "حذر",
        "warn_hepatic": "",
        "warn_allergy": "",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Meloxicam - ميلوكسيكام",
        "category": "المسكنات (Analgesics)",
        "forms": ["أقراص", "حقنة", "تحاميل"],
        "doses_adult": ["7.5-15mg"],
        "doses_child": ["0.125mg/kg"],
        "doses_elderly": [],
        "timing": ["مرة واحدة يومياً"],
        "duration": ["حسب الحالة"],
        "note": "الأقل تأثيراً على المعدة من بين NSAIDs.",
        "warn_pregnant": "ممنوع في الثلث الأخير",
        "warn_breastfeed": "",
        "warn_renal": "",
        "warn_hepatic": "",
        "warn_allergy": "يُتجنب لمرضى الربو",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Indomethacin - إندوميتاسين",
        "category": "المسكنات (Analgesics)",
        "forms": ["كبسول", "حقنة", "تحاميل"],
        "doses_adult": ["25-50mg"],
        "doses_child": [],
        "doses_elderly": [],
        "timing": ["مرتان يومياً", "ثلاث مرات يومياً"],
        "duration": ["حسب الحاجة"],
        "note": "الأقوى والأخطر في NSAIDs. يرفع الضغط داخل الجمجمة.",
        "warn_pregnant": "ممنوع",
        "warn_breastfeed": "",
        "warn_renal": "",
        "warn_hepatic": "",
        "warn_allergy": "ممنوع لمرضى الربو",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Celecoxib - سيليكوكسيب",
        "category": "المسكنات (Analgesics)",
        "forms": ["كبسول"],
        "doses_adult": ["100-200mg"],
        "doses_child": [],
        "doses_elderly": [],
        "timing": ["مرة واحدة يومياً", "مرتان يومياً"],
        "duration": ["حسب الحالة"],
        "note": "أقل ضرراً للمعدة. خطر جلطات قلبية عند الاستخدام طويل الأمد.",
        "warn_pregnant": "ممنوع في الثلث الأخير",
        "warn_breastfeed": "",
        "warn_renal": "",
        "warn_hepatic": "",
        "warn_allergy": "",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Colchicine - كولشيسين",
        "category": "المسكنات (Analgesics)",
        "forms": ["كبسول"],
        "doses_adult": ["0.6mg"],
        "doses_child": [],
        "doses_elderly": [],
        "timing": ["مرتان يومياً", "ثلاث مرات يومياً"],
        "duration": ["3-5 أيام"],
        "note": "يُستخدم فقط للنقرس.",
        "warn_pregnant": "يُتجنب",
        "warn_breastfeed": "",
        "warn_renal": "تخفيض الجرعة",
        "warn_hepatic": "تخفيض الجرعة",
        "warn_allergy": "",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Morphine - مورفين",
        "category": "المسكنات (Analgesics)",
        "forms": ["أقراص", "شراب", "حقنة"],
        "doses_adult": ["5-15mg (فموي)", "2-4mg (حقن)"],
        "doses_child": ["0.1-0.2mg/kg"],
        "doses_elderly": [],
        "timing": ["كل 4 ساعات"],
        "duration": ["حسب الحاجة"],
        "note": "ممنوع عند مشاكل التنفس. يسبب إدمان شديد.",
        "warn_pregnant": "يُتجنب",
        "warn_breastfeed": "ممنوع",
        "warn_renal": "",
        "warn_hepatic": "",
        "warn_allergy": "",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Codeine - كودايين",
        "category": "المسكنات (Analgesics)",
        "forms": ["أقراص", "شراب"],
        "doses_adult": ["30-60mg"],
        "doses_child": [],
        "doses_elderly": [],
        "timing": ["كل 4-6 ساعات"],
        "duration": ["3-5 أيام"],
        "note": "الأطفال <12 سنة: ممنوع. الأفضل لتثبيط السعال.",
        "warn_pregnant": "يُتجنب",
        "warn_breastfeed": "ممنوع",
        "warn_renal": "",
        "warn_hepatic": "",
        "warn_allergy": "",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Tramadol - ترامادول",
        "category": "المسكنات (Analgesics)",
        "forms": ["أقراص", "شراب", "حقنة"],
        "doses_adult": ["50-100mg"],
        "doses_child": ["1-2mg/kg"],
        "doses_elderly": [],
        "timing": ["كل 4-6 ساعات"],
        "duration": ["حسب الحالة"],
        "note": "أقل إدماناً من المورفين. يسبب متلازمة السيروتونين مع مضادات الاكتئاب.",
        "warn_pregnant": "يُتجنب",
        "warn_breastfeed": "ممنوع",
        "warn_renal": "تخفيض الجرعة",
        "warn_hepatic": "",
        "warn_allergy": "",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Fentanyl - فنتانيل",
        "category": "المسكنات (Analgesics)",
        "forms": ["حقنة", "لصقة"],
        "doses_adult": ["25-100mcg"],
        "doses_child": ["1-2mcg/kg"],
        "doses_elderly": [],
        "timing": ["حسب إشراف الطبيب"],
        "duration": ["حسب الحالة"],
        "note": "أقوى 100 مرة من المورفين.",
        "warn_pregnant": "ممنوع",
        "warn_breastfeed": "",
        "warn_renal": "",
        "warn_hepatic": "",
        "warn_allergy": "",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Amitriptyline - أميتريبتيلين",
        "category": "المسكنات (Analgesics)",
        "forms": ["أقراص"],
        "doses_adult": ["10-25mg"],
        "doses_child": [],
        "doses_elderly": ["10mg"],
        "timing": ["مرة واحدة يومياً (قبل النوم)"],
        "duration": ["أشهر"],
        "note": "يسبب نعاساً شديداً. ممنوع عند احتشاء القلب.",
        "warn_pregnant": "حذر",
        "warn_breastfeed": "",
        "warn_renal": "",
        "warn_hepatic": "",
        "warn_allergy": "",
        "warn_diabetes": "يرفع نسبة السكر",
        "warn_blood_pressure": ""
    },
    {
        "name": "Duloxetine - دولوكسيتين",
        "category": "المسكنات (Analgesics)",
        "forms": ["كبسول"],
        "doses_adult": ["30-60mg"],
        "doses_child": [],
        "doses_elderly": [],
        "timing": ["مرة واحدة يومياً"],
        "duration": ["أشهر"],
        "note": "مسكن الألم العصبي السكري. لا يوقف فجأة.",
        "warn_pregnant": "يُتجنب",
        "warn_breastfeed": "",
        "warn_renal": "تخفيض الجرعة",
        "warn_hepatic": "ممنوع",
        "warn_allergy": "",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Sumatriptan / Zolmitriptan / Rizatriptan - سوماتريبتان",
        "category": "المسكنات (Analgesics)",
        "forms": ["أقراص", "بخاخ", "حقنة"],
        "doses_adult": ["50-100mg"],
        "doses_child": ["25-50mg (>12 سنة)"],
        "doses_elderly": [],
        "timing": ["عند بداية النوبة"],
        "duration": ["جرعة واحدة للنوبة"],
        "note": "مسكن خاص بالشقيقة. ممنوع عند أمراض القلب.",
        "warn_pregnant": "يُتجنب",
        "warn_breastfeed": "",
        "warn_renal": "",
        "warn_hepatic": "",
        "warn_allergy": "",
        "warn_diabetes": "",
        "warn_blood_pressure": "ممنوع عند ارتفاع الضغط الشديد"
    },
    {
        "name": "Methotrexate - ميثوتريكسات",
        "category": "المسكنات (Analgesics)",
        "forms": ["أقراص", "حقنة"],
        "doses_adult": ["7.5-25mg"],
        "doses_child": ["10mg/m2"],
        "doses_elderly": [],
        "timing": ["مرة واحدة أسبوعياً"],
        "duration": ["أشهر إلى سنوات"],
        "note": "معدل مسار الروماتيزم. مثبط مناعي قوي.",
        "warn_pregnant": "ممنوع تماماً - مشوه",
        "warn_breastfeed": "ممنوع",
        "warn_renal": "ممنوع",
        "warn_hepatic": "يسبب تشمع الكبد",
        "warn_allergy": "",
        "warn_diabetes": "",
        "warn_blood_pressure": ""
    },
    {
        "name": "Hydroxychloroquine (Plaquenil) - هيدروكسي كلوروكين",
        "category": "المسكنات (Analgesics)",
        "forms": ["أقراص"],
        "doses_adult": ["200-400mg"],
        "doses_child": ["5mg/kg"],
        "doses_elderly": [],
        "timing": ["مرة واحدة يومياً"],
        "duration": ["أشهر إلى سنوات"],
        "note": "يسبب تلفاً في الشبكية. فحص عيون دوري ضروري.",
        "warn_pregnant": "بإشراف طبي",
        "warn_breastfeed": "",
        "warn_renal": "",
        "warn_hepatic": "",
        "warn_allergy": "",
        "warn_diabetes": "قد يخفض السكر",
        "warn_blood_pressure": ""
    }
]

def main():
    if not os.path.exists(db_path):
        print("Database file 'clinic.db' not found. Ensure backend is running once to create it.")
        return

    conn = sqlite3.connect(db_path)
    cur = conn.cursor()
    
    count = 0
    for d in drugs_data:
        try:
            cur.execute("""
                INSERT INTO drugs (name, category, forms, doses_adult, doses_child, doses_elderly, timing, duration, note, warn_pregnant, warn_breastfeed, warn_renal, warn_hepatic, warn_allergy, warn_diabetes, warn_blood_pressure, is_custom)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1)
            """, (
                d["name"], d["category"],
                json.dumps(d["forms"], ensure_ascii=False),
                json.dumps(d["doses_adult"], ensure_ascii=False),
                json.dumps(d["doses_child"], ensure_ascii=False),
                json.dumps(d["doses_elderly"], ensure_ascii=False),
                json.dumps(d["timing"], ensure_ascii=False),
                json.dumps(d["duration"], ensure_ascii=False),
                d["note"], d["warn_pregnant"], d["warn_breastfeed"],
                d["warn_renal"], d["warn_hepatic"],
                d["warn_allergy"], d["warn_diabetes"], d["warn_blood_pressure"]
            ))
            count += 1
        except sqlite3.IntegrityError:
            print(f"Skipped {d['name']} - already exists.")
        except Exception as e:
            print(f"Error inserting {d['name']}: {e}")

    conn.commit()
    conn.close()
    print(f"Successfully inserted {count} drugs into the database!")

if __name__ == "__main__":
    main()
