import React, { createContext, useContext, useState, useEffect } from "react";

const translations = {
  en: {
    "الرئيسية": "Dashboard",
    "المرضى": "Patients",
    "المواعيد": "Appointments",
    "الفواتير": "Invoices",
    "التقارير": "Reports",
    "الإعدادات": "Settings",
    "SmileCare": "SmileCare",
    
    // Home
    "مواعيد اليوم": "Today's Appointments",
    "مرضى جدد هذا الأسبوع": "New Patients This Week",
    "إيرادات اليوم": "Today's Revenue",
    "مبالغ مستحقة": "Outstanding Amounts",
    "لا توجد مواعيد اليوم": "No appointments today",
    "إجراءات سريعة": "Quick Actions",
    "موعد جديد": "New Appointment",
    "مريض جديد": "New Patient",
    "فاتورة جديدة": "New Invoice",
    " د": " IQD",
    
    // Statuses
    "مكتمل": "Completed",
    "قادم": "Upcoming",
    "لاحقاً": "Later",
    "ملغي": "Cancelled",
    "جديد": "New",
    "منتظم": "Regular",
    "مديون": "In Debt",
    "مدفوع": "Paid",
    "جزئي": "Partial",
    "مستحق": "Due",
    "ذكر": "Male",
    "أنثى": "Female",
    
    // Patients
    "ابحث بالاسم أو الهاتف...": "Search by name or phone...",
    "جميع المرضى": "All Patients",
    "+ إضافة مريض": "+ Add Patient",
    "المريض": "Patient",
    "الهاتف": "Phone",
    "العمر": "Age",
    "آخر زيارة": "Last Visit",
    "الحالة": "Status",
    "إجراءات": "Actions",
    " سنة": " Years",
    "لا توجد": "None",
    "ملف": "Profile",
    "موعد": "Appt",
    "لا توجد نتائج": "No results",
    " مريض": " Patients",
    "إضافة مريض جديد": "Add New Patient",
    "الاسم الأول *": "First Name *",
    "اسم العائلة *": "Last Name *",
    "رقم الهاتف": "Phone Number",
    "تاريخ الميلاد": "Birth Date",
    "الجنس": "Gender",
    "فصيلة الدم": "Blood Type",
    "البريد الإلكتروني": "Email",
    "العنوان": "Address",
    "الحساسيات / ملاحظات طبية": "Allergies / Medical Notes",
    "ملاحظات الطبيب": "Doctor's Notes",
    "إلغاء": "Cancel",
    "حفظ المريض": "Save Patient",
    "جاري الحفظ...": "Saving...",
    "الرجاء إدخال الاسم": "Please enter name",
    
    // Patient Profile
    "البيانات": "Info",
    "الزيارات": "Visits",
    "خريطة الأسنان": "Tooth Map",
    "الحساب": "Finance",
    "زيارة": "Visit",
    "الحساب مسوّى": "Balance Clear",
    "+ زيارة جديدة": "+ New Visit",
    "+ فاتورة": "+ Invoice",
    "← رجوع": "← Back",
    "البيانات الشخصية": "Personal Info",
    "الاسم الكامل": "Full Name",
    "البريد": "Email",
    "السجل الطبي": "Medical Record",
    "الحساسيات": "Allergies",
    "أمراض مزمنة": "Chronic Diseases",
    "لا يوجد": "None",
    "أدوية دائمة": "Medications",
    "تاريخ أول زيارة": "First Visit",
    "عدد الزيارات": "Visit Count",
    "ملاحظات:": "Notes:",
    "إجمالي الزيارات": "Total Visits",
    "إجمالي الفواتير": "Total Invoices",
    "المستحق": "Due Amount",
    "سجل الزيارات": "Visit History",
    "لا توجد زيارات مسجلة": "No recorded visits",
    "خريطة الأسنان — اضغط على أي سن لتغيير حالته": "Tooth Map - Click to change status",
    "حفظ الخريطة": "Save Map",
    "الفك العلوي": "Upper Jaw",
    "الفك السفلي": "Lower Jaw",
    "سليم": "Healthy",
    "حشو": "Filling",
    "تلبيس": "Crown",
    "مفقود": "Missing",
    "تحت علاج": "Under Treatment",
    "المدفوع": "Paid",
    "سجل الفواتير": "Invoice History",
    "لا توجد فواتير": "No invoices",
    "التاريخ *": "Date *",
    "نوع العلاج *": "Treatment Type *",
    "التكلفة (د)": "Cost ($)",
    "ملاحظات": "Notes",
    "حفظ الزيارة": "Save Visit",
    "المبلغ الإجمالي (د) *": "Total Amount ($) *",
    "المبلغ المدفوع (د)": "Paid Amount ($)",
    "تم حفظ خريطة الأسنان ✓": "Tooth map saved ✓",
    "أدخل التاريخ ونوع العلاج": "Enter date and treatment type",
    "أدخل المبلغ": "Enter amount",
    "جاري التحميل...": "Loading...",
    
    // Appointments
    "أح": "Sun", "اث": "Mon", "ثل": "Tue", "أر": "Wed", "خم": "Thu", "جم": "Fri", "سب": "Sat",
    "يناير": "January", "فبراير": "February", "مارس": "March", "أبريل": "April", "مايو": "May", "يونيو": "June",
    "يوليو": "July", "أغسطس": "August", "سبتمبر": "September", "أكتوبر": "October", "نوفمبر": "November", "ديسمبر": "December",
    "مواعيد": "Appts",
    "لا توجد مواعيد في هذا اليوم": "No appointments today",
    "دقيقة": "min",
    "تعديل": "Edit",
    "حذف": "Delete",
    "جميع المواعيد القادمة": "Upcoming Appointments",
    "التاريخ": "Date",
    "الوقت": "Time",
    "العلاج": "Treatment",
    "المدة": "Duration",
    "إجراء": "Action",
    "د": "IQD",
    "تعديل الموعد": "Edit Appointment",
    "إضافة موعد جديد": "Add Appointment",
    "المريض *": "Patient *",
    "اختر مريضاً...": "Select Patient...",
    "الوقت *": "Time *",
    "نوع العلاج": "Treatment Type",
    "اختر...": "Select...",
    "المدة (دقيقة)": "Duration (min)",
    "فحص دوري": "Checkup", "تنظيف أسنان": "Cleaning", "حشو ضرس": "Filling", "خلع ضرس": "Extraction",
    "تقويم أسنان": "Braces", "تبييض أسنان": "Whitening", "تلبيس ضرس": "Crown", "علاج عصب": "Root Canal",
    "زراعة": "Implant", "أشعة": "X-Ray", "استشارة": "Consultation",
    "أدخل المريض والتاريخ والوقت": "Enter patient, date and time",
    "هل تريد حذف هذا الموعد؟": "Delete this appointment?",
    
    // Treatments
    "سجل العلاج (تاريخ السن)": "Treatment Log (History per Tooth)",
    "+ إضافة إجراء جديد": "+ Log New Procedure",
    "لا توجد سجلات علاجية بعد.": "No treatments logged yet.",
    "رقم السن (مثال: 46، 11، الكل)": "Tooth Number (e.g., 46, 11, All)",
    "الإجراء": "Procedure",
    "ملاحظات طبية": "Clinical Notes",
    "التكلفة (اختياري)": "Cost (Optional)",
    "الأجر": "Fee",
    "هل تريد حذف هذا السجل؟": "Delete this log?",
    "حفظ الإجراء": "Save Procedure",
    "تسجيل إجراء جديد": "Log New Procedure",
    "خطة العلاج": "Treatment Plan",

    "تذكيرات مواعيد الغد": "Tomorrow's Reminders",
    "لا توجد مواعيد ليوم غد": "No appointments for tomorrow",
    "بدون رقم هاتف": "No phone number",
    "إرسال تذكيرات الغد": "Send Tomorrow's Reminders",

    // Invoices
    "إجمالي الشهر": "Monthly Total",
    "المحصّل": "Collected",
    "عدد الفواتير": "Invoices Count",
    "ابحث باسم المريض...": "Search by patient name...",
    "جميع الفواتير": "All Invoices",
    "+ فاتورة جديدة": "+ New Invoice",
    "#": "#",
    "تحصيل": "Collect",
    "طباعة": "Print",
    "إضافة فاتورة جديدة": "Add New Invoice",
    "تحصيل دفعة —": "Collect payment —",
    "تأكيد التحصيل": "Confirm Collection",
    "أدخل المريض والمبلغ": "Enter patient and amount",
    
    // Reports
    "🖨 طباعة التقرير": "🖨 Print Report",
    "إجمالي الإيرادات (د)": "Total Revenue ($)",
    "المحصّل (د)": "Collected ($)",
    "المستحق (د)": "Due ($)",
    "مريض جديد هذا الشهر": "New Patients This Month",
    "الإيرادات الشهرية (د) —": "Monthly Revenue ($) —",
    "أكثر الخدمات طلباً": "Top Services",
    "لا توجد بيانات": "No data",
    "الملخص المالي —": "Financial Summary —",
    "متوسط الفاتورة": "Average Invoice",
    "حالة المواعيد": "Appt Status",
    "الإجمالي": "Total",
    "طباعة التقرير": "Print Report",
    
    // Settings
    "بيانات العيادة": "Clinic Info",
    "اسم العيادة": "Clinic Name",
    "اسم الطبيب": "Doctor Name",
    "عنوان العيادة": "Clinic Address",
    "✓ تم الحفظ": "✓ Saved",
    "حفظ التغييرات": "Save Changes",
    "النسخ الاحتياطي": "Backup",
    "نسخ احتياطي تلقائي": "Auto Backup",
    "يومياً الساعة 11 مساءً": "Daily at 11 PM",
    "مجلد الحفظ": "Storage Folder",
    "تغيير": "Change",
    "نسخ احتياطي الآن": "Backup Now",
    "إعدادات النظام": "System Settings",
    "تذكير بالمواعيد": "Appointment Reminders",
    "قبل الموعد بساعة": "1 hour before",
    "تنبيهات الديون": "Debt Alerts",
    "عند وجود مبالغ مستحقة": "When amounts are due",
    "الوضع الليلي": "Dark Mode",
    "تغيير مظهر النظام": "Change appearance",
    "طباعة الفاتورة تلقائياً": "Auto-print Invoices",
    "عند إتمام كل زيارة": "After each visit",
    "معلومات الترخيص": "License Info",
    "مفتاح الترخيص": "License Key",
    "غير مفعّل": "Not Activated",
    "صالح حتى ": "Valid until ",
    "لا يوجد ترخيص نشط": "No active license",
    "إدخال مفتاح ترخيص جديد": "Enter new license key",
    "تفعيل": "Activate",
    "إصدار النظام": "System Version",
    
    // Case Presentation
    "عرض الحالة": "Case Presentation",
    "خريطة الفكين": "Jaw Map",
    "ملاحظات العمل": "Work Notes",
    "ملاحظات العمل...": "Work notes...",
    "إضافة ملاحظة": "Add Note",
    "وصف الصورة...": "Image description...",
    "طباعة كرت الحالة": "Print Casesheet",
    "Upper Right": "Upper Right",
    "Upper Left": "Upper Left",
    "Lower Right": "Lower Right",
    "Lower Left": "Lower Left",
    "الصور": "Images",
    "اضغط لإضافة صورة": "Click to add image",
    "بيانات عرض الحالة الأولية": "Initial Case Data",
    "تم حفظ بيانات عرض الحالة بنجاح ✓": "Case data saved successfully ✓",
    "حدث خطأ أثناء الحفظ": "An error occurred while saving",
    "حفظ البيانات": "Save Data",
    
    // Expenses
    "المصاريف": "Expenses",
    "إجمالي المصاريف": "Total Expenses",
    "+ إضافة مصروف": "+ Add Expense",
    "إضافة مصروف جديد": "Add New Expense",
    "الفئة": "Category",
    "الفئة *": "Category *",
    "إيجار": "Rent",
    "مواد طبية": "Medical Supplies",
    "كهرباء ومياه": "Utilities",
    "رواتب": "Salaries",
    "صيانة": "Maintenance",
    "إعلان": "Advertising",
    "أخرى": "Others",
    "هل تريد حذف هذا البند؟": "Do you want to delete this item?",
    "لا توجد مصاريف مسجلة": "No recorded expenses",
    
    // Prescriptions
    "الوصفات": "Prescriptions",
    "الوصفات الطبية السابقة": "Previous Prescriptions",
    "+ وصفة جديدة": "+ New Prescription",
    "إضافة وصفة طبية جديدة": "Add New Prescription",
    "الأدوية والجرعات *": "Medications & Dosages *",
    "ملاحظات إضافية": "Additional Notes",
    "حفظ الوصفة": "Save Prescription",
    "وصفة طبية": "Prescription",
    "لا توجد وصفات مسجلة": "No recorded prescriptions",
    "أدخل الأدوية": "Enter medications",
    "صافي المحصل": "Net Collected",
    "المواد والتشغيل": "Supplies & Ops",
    "بعد خصم المصاريف": "After expenses",
    "ديون لم تحصل": "Uncollected debts",
    "قائمة المديونيات": "Debt List",
    "إجمالي الديون المستحقة": "Total Outstanding Debts",
    "لا توجد ديون مستحقة ✓": "No outstanding debts ✓",
    "إجمالي العلاج": "Total Treatment",
    "المبلغ المتبقي": "Remaining Amount",
    "الديون": "Debts",
    
    // Newly Added
    "المصاريف التشغيلية": "Operational Expenses",
    "إجمالي المصاريف المسجلة": "Total Recorded Expenses",
    "Cash (الخزنة)": "Cash",
    "Bank (البنك)": "Bank",
    "الفواتير والمدفوعات": "Invoices & Payments",
    "المبالغ المحصلة": "Collected Amounts",
    "الديون المتبقية": "Remaining Debts",
    "إدارة المواعيد": "Appointments Management",
    "إدارة المرضى": "Patients Management",
    "Occupation": "Occupation",
    "نوع الحالة": "Case Category",
    "إجمالي المبلغ المتفق عليه": "Total Agreed Amount",
    "المبلغ المدفوع كلياً": "Total Paid Amount",
    "المبلغ المتبقي (دين)": "Remaining Amount (Debt)",
    "سجل الدفعات": "Payments History",
    "+ إضافة دفعة": "+ Add Payment",
    "لا توجد دفعات مسجلة": "No recorded payments",
    "المبلغ": "Amount",
    "أدخل أي ملاحظات حول الدفعة": "Enter any notes about the payment",
    "إضافة": "Add",
    "تعديل المبلغ الكلي:": "Edit total amount:",
    "الدفعة الأولى عند التسجيل": "Initial Registration Payment",
    "جميع الحالات": "All Statuses",
    "فتح الملف": "Open Profile",
    "السعر الكلي المتفق عليه": "Total Agreed Price",
    "الدفعة الأولى": "First Payment",
    "ملف المريض": "Patient Profile",
    "جدول المواعيد الحالية": "Current Appointments",
    "عرض الكل": "View All",
    "لا توجد مواعيد متبقية لليوم": "No remaining appointments for today",
    "الوصول السريع": "Quick Access",
    "نصيحة اليوم": "Tip of the Day",
    "تأكد من مراجعة الحالات الطبية المسجلة للمريض قبل البدء في أي إجراء جراحي اليوم.": "Ensure you review the patient's medical history before any surgical procedure today.",
    "فاتورة": "Invoice",
    
    // Final Fixes from review
    "سجل الوصفات الطبية": "Prescription History",
    "أهلاً بك": "Welcome",
    "النظام متصل": "System Online",
    "تسجيل الخروج": "Logout",
    "الطبيب": "Doctor",
    "إضافة مصروف": "Add Expense",
    "إضافة وصفة طبية (صورة)": "Add Prescription (Image)",
    "اضغط لتصوير أو اختيار صورة الوصفة": "Click to capture or select prescription photo",
    "وصفات مسجلة": "Recorded Prescriptions",
    "رجوع لقائمة المرضى": "Back to Patients List",
    "فتح الملف الشخصي": "Open Profile",
    "بحث باسم المريض...": "Search by patient name...",
    "المريض موجود بالفعل": "Patient already exists",
    "إضافة سريع": "Quick Add",
    "بحث عن مريض...": "Search for patient...",
    "لا يوجد مريض بهذا الاسم": "No patient with this name",
    "يمكنك الضغط على إضافة سريع لإنشاء حساب له": "Click Quick Add to create an account",
    "خطأ في إضافة المريض": "Error adding patient",
    "سجل حركات النظام": "System Activity Log",
    "كل المستخدمين": "All Users",
    "الطبيب فقط": "Doctor Only",
    "السكرتارية فقط": "Secretary Only",
    "سجل الحركات والمراقبة": "Activity & Audit Log",
    "متابعة كل ما يتم في النظام لحظة بلحظة": "Monitor everything in the system moment by moment",
    "جاري تحميل السجلات...": "Loading logs...",
    "لا توجد حركات مسجلة بعد.": "No activity recorded yet.",

    "المستخدم": "User",
    "العملية": "Action",
    "الهدف": "Target",
    "الوصف": "Description",
    "تسجيل دخول": "Login",
    "تسجيل خروج": "Logout",
    "إضافة مريض": "Add Patient",
    "تعديل مريض": "Update Patient",
    "حذف مريض": "Delete Patient",
    "فتح ملف": "Open Profile",
    "إضافة فاتورة": "Add Invoice",
    "تسديد مبلغ": "Payment Collected",
    "حذف فاتورة": "Delete Invoice",
    "تعديل خريطة الأسنان": "Update Tooth Map",
    "إضافة إجراء علاجي": "Add Treatment Log",
    "استعادة البيانات من نسخة احتياطية": "Restore Data from Backup",
    "تحذير: سيتم استبدال جميع البيانات الحالية بالبيانات الموجودة في الملف المرفوع. هل أنت متأكد؟": "Warning: All current data will be replaced by the uploaded file. Are you sure?",
    "✓ تمت استعادة البيانات بنجاح. سيتم إعادة تحميل الصفحة.": "✓ Data restored successfully. Reloading page...",
    "✓ تمت معالجة الطلب. سيتم إعادة تحميل الصفحة للتأكد من استرجاع البيانات.": "✓ Request processed. Reloading page to verify data restoration.",
    "خطأ: ": "Error: ",
    "نسخ احتياطي شخصي (Google Drive)": "Personal Cloud Backup (Google Drive)",
    "ربط حساب Google Drive الشخصي": "Link Personal Google Drive Account",
    "تصفير كافة بيانات العيادة (خطر)": "Zero Out All Clinic Data (Danger)",
    "⚠️ تحذير شديد: سيتم مسح كافة سجلات المرضى والفواتير والمواعيد والمصاريف نهائياً. هل أنت متأكد؟": "⚠️ Extreme Warning: All patients, invoices, appointments, and expenses will be permanently deleted. Are you sure?",
    "يرجى إدخال كلمة مرور الحساب للتأكيد:": "Please enter account password to confirm:",
    "✓ تم تصفير كافة بيانات العيادة بنجاح.": "✓ All clinic data has been successfully zeroed out.",
    "مرتبط حالياً": "Linked Currently",
    "ربط الحساب": "Link Account",
    "هل تريد إلغاء ربط Google Drive؟": "Do you want to unlink Google Drive?",
    "رفع نسخة تلقائية لحسابك الشخصي يومياً": "Upload automatic backup to your personal account daily",
    "ملخص الجرد اليومي": "Daily Audit Summary",
    "جرد المقبوضات والمصاريف والحالات اليوم": "Daily tally of receipts, expenses, and cases",
    "بيانات العيادة ليوم": "Clinic data for",
    "إجمالي المقبوضات": "Total Receipts",

    "صافي الربح اليومي": "Daily Net Profit",
    "مرضى اليوم": "Today's Patients",
    "المقبوضات المالية اليوم": "Today's Financial Receipts",
    "لا توجد فواتير اليوم": "No invoices today",
    "المصاريف المدفوعة اليوم": "Expenses Paid Today",
    "لا توجد مصاريف اليوم": "No expenses today",
    "نشاط المواعيد والحالات اليوم": "Today's Appointments & Cases activity",
    "لا توجد مواعيد مسجلة اليوم": "No appointments registered today",
    "جاري تحميل الملخص اليومي...": "Loading daily summary...",

    "وصفة": "Prescription",
    "ملخص الجرد اليومي الشامل": "Comprehensive Daily Audit Summary",
    "طباعة التقرير الختامي": "Print Closing Report",
    "نقداً": "Cash",
    "بنك": "Bank",
    "معالج": "Treated",
    "جدد": "New",
    "تفاصيل التدفق المالي": "Financial Flow Details",
    "لا توجد حركات مالية اليوم": "No financial transactions today",
    "السجل الطبي السريع (الإجراءات)": "Quick Medical Record (Procedures)",
    "لم يتم تسجيل إجراءات طبية اليوم": "No medical procedures recorded today",
    "استهلاك المخزن اليومي": "Daily Inventory Consumption",
    "لم يتم تسجيل استهلاك مواد اليوم": "No inventory consumption recorded today",
    "حالة مواعيد اليوم": "Today's Appointments Status",
    "اكتملت": "Completed",
    "لم تحضر": "No-Show"
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(localStorage.getItem("clinic_lang") || "ar");

  useEffect(() => {
    localStorage.setItem("clinic_lang", lang);
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
  }, [lang]);

  const toggleLanguage = () => {
    setLang((prev) => (prev === "ar" ? "en" : "ar"));
  };

  const t = (key) => {
    if (lang === "ar") return key; // Default keys are in Arabic
    return translations[lang]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
